---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.0.30
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.0.0.40
        k8s-2:
          ansible_host: 10.0.0.41
