---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.0.30
          rook_block_device: /dev/disk/by-id/ata-TEAM_T253X6001T_TPBF2101280010400531
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.0.0.40
          rook_block_device: /dev/disk/by-id/ata-TEAM_T253X6001T_TPBF2101280010400526
        k8s-2:
          ansible_host: 10.0.0.41
          rook_block_device: /dev/disk/by-id/ata-TEAM_T253X6001T_TPBF2101280010400471
