---
kubernetes:
  children:
    master:
      hosts:
        ks8-control-0:
          ansible_host: 10.0.0.50
        k8s-control-1:
          ansible_host: 10.0.0.51
        k8s-control-2:
          ansible_host: 10.0.0.52
    worker:
      hosts:
        k8s-worker-0:
          ansible_host: 10.0.0.60
        k8s-worker-1:
          ansible_host: 10.0.0.61
        k8s-worker-2:
          ansible_host: 10.0.0.62
        k8s-worker-3:
          ansible_host: 10.0.0.63
