kind: Secret
ansible_user: ENC[AES256_GCM,data:XMr7ZK68,iv:45fZpufIOSF9uMZCpAaNUpsEVBcfJh2QpqjfoJyY8Fs=,tag:Uf68cU/i13Hvc0rCLI4H6w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LdMz3XjRwkg=,iv:vh9Ey6z29pbQa4ucQfpxaK1pua/OuwuRe1Q6fiKa8X8=,tag:RYi1w2tA3sIdAW88mMzR7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjps0r22shgaytpmesd88ashlxea4feaqyzay3lraajet9mz2s0qpgxey0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXpBcW5wMEtiOWFXNkZH
            TjhTWEgxWW55N2d5OW9SRWdwK2RyVzlBTGxVClRSdWZLMUl4Q2RnMU5yNlJ0RXZv
            Vm5NOHRLRHVWY29wdkF0MzlMc0Rtb2cKLS0tIGJsVXFkMmVqZGw0bUVtcU95THIz
            eG85RERUbFRBQisyeFFNVnRSZVZtVW8K/4Y6JJ7FTmdbbJQ0dmE0wFDYxb4MWJmW
            oETiTSWApwZU3QwIwDX2Uvb2pWog4bBRoyglKIbcpqu9TDC/KqNE6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T09:30:36Z"
    mac: ENC[AES256_GCM,data:qWm9sVvHXYGNc29r657Wjj5Iv9uxPLiBr4gKO3KTFJ3hmI3IuVGt2T5bWNvdVycS1MnW8Jnxyh77B94VTw5cHcV6zYetKSwS3yauxU4Olu7CjNH6mrFv8YMMaxNpsWeSgq23t/8vdeDGKdxchosEI2J5rA2CbT39wSXT2LlN2KQ=,iv:gVu0lBO5MxhkbU8bHdA4qKnfj8FnFsjfDAupl8dxWpA=,tag:1ekcO6MYzK2wZHLoz6QWsw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
